version: "3.9"

services:
  db:
    image: mysql:8.4
    container_name: cakedaddy-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cakedaddy
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: cakedaddy
      MYSQL_PASSWORD: cakesecret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend      # folder that contains the Dockerfile
    container_name: cakedaddy-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cakedaddy
      SPRING_DATASOURCE_USERNAME: cakedaddy
      SPRING_DATASOURCE_PASSWORD: cakesecret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Any other Spring Boot env keys go here
    ports:
      - "8080:8080"

volumes:
  db_data:
